// ============================================================
// 活人泰语点读卡 — 数据文件
// 内容来源：《来泰国后真的能用上的活人泰语》PDF
// 语气词已统一为女性用语（ค่ะ/คะ）
// ============================================================

const CATEGORIES = [
  { id: 'rent',      icon: '🏠', title: '租房',           desc: '找房子、问价格、看房、签合同',   color: '#FF6B9D', bg: '#FFE0EC' },
  { id: 'grab',      icon: '🚗', title: 'Grab打车',       desc: '叫车、指路、跟司机沟通',         color: '#A78BFA', bg: '#EDE5FF' },
  { id: 'restaurant',icon: '🍜', title: '餐厅',           desc: '点餐、辣度、买单、打包',         color: '#FB923C', bg: '#FFEDD5' },
  { id: 'seven11',   icon: '🏪', title: '7-11便利店',     desc: '加热、要袋子、退税、付款',       color: '#34D399', bg: '#D1FAE5' },
  { id: 'massage',   icon: '💆', title: '按摩',           desc: '选项目、力度、时间、加钟',       color: '#F472B6', bg: '#FCE7F3' },
  { id: 'doctor',    icon: '🏥', title: '看病',           desc: '描述症状、告诉医生哪里不舒服',   color: '#60A5FA', bg: '#DBEAFE' },
  { id: 'love',      icon: '💕', title: '恋爱',           desc: '表白、暧昧、恋爱中的甜言蜜语',   color: '#F472B6', bg: '#FCE7F3' },
  { id: 'friend',    icon: '👋', title: '交友',           desc: '加LINE、聊社交、认识新朋友',     color: '#FBBF24', bg: '#FEF3C7' },
  { id: 'shopping',  icon: '🛍️', title: '购物',           desc: '砍价、试穿、尺码、颜色',         color: '#A78BFA', bg: '#EDE5FF' },
  { id: 'daily',     icon: '☀️', title: '100句·日常用语',  desc: '打招呼、感谢、道歉、基本表达',   color: '#FB923C', bg: '#FFEDD5' },
  { id: 'daily-shop',icon: '🛒', title: '100句·购物用语',  desc: '逛街、市场、砍价必用句',         color: '#34D399', bg: '#D1FAE5' },
  { id: 'daily-eat', icon: '🍽️', title: '100句·餐饮用语',  desc: '点菜、口味、结账、外卖',         color: '#F472B6', bg: '#FCE7F3' },
  { id: 'daily-go',  icon: '✈️', title: '100句·出行用语',  desc: '机场、打车、问路、酒店',         color: '#60A5FA', bg: '#DBEAFE' },
  { id: 'daily-social',icon:'💬', title: '100句·社交用语', desc: '聊天、追星、网络社交',           color: '#FBBF24', bg: '#FEF3C7' },
];

const SENTENCES = [
  // ===== Part 1: 租房 =====
  { id: 1, cat: 'rent', thai: 'มีห้องให้เช่าไหมคะ', cn: '有房间出租吗？', pron: 'mee hong hai chao mai ka', scene: '打电话或到公寓前台问是否有空房', diff: '入门', tone: '日常', gender: 'female', tags: ['租房', '问房'] },
  { id: 2, cat: 'rent', thai: 'เช่าเดือนละเท่าไหร่คะ', cn: '月租多少钱？', pron: 'chao duean la thao rai ka', scene: '询问月租金价格', diff: '入门', tone: '日常', gender: 'female', tags: ['租房', '问价'] },
  { id: 3, cat: 'rent', thai: 'ค่ามัดจำเท่าไหร่คะ', cn: '押金多少钱？', pron: 'kha mat jam thao rai ka', scene: '询问押金金额', diff: '常用', tone: '日常', gender: 'female', tags: ['租房', '押金'] },
  { id: 4, cat: 'rent', thai: 'รวมน้ำรวมไฟไหมคะ', cn: '包水电吗？', pron: 'ruam nam ruam fai mai ka', scene: '问租金是否含水电网费', diff: '常用', tone: '日常', gender: 'female', tags: ['租房', '水电'] },
  { id: 5, cat: 'rent', thai: 'มีแอร์ไหมคะ', cn: '有空调吗？', pron: 'mee ae mai ka', scene: '看房时问设施', diff: '入门', tone: '日常', gender: 'female', tags: ['租房', '空调'] },
  { id: 6, cat: 'rent', thai: 'มีWiFiไหมคะ', cn: '有WiFi吗？', pron: 'mee wifi mai ka', scene: '询问网络', diff: '入门', tone: '日常', gender: 'female', tags: ['租房', '网络'] },
  { id: 7, cat: 'rent', thai: 'ขอดูห้องก่อนได้ไหมคะ', cn: '可以先看看房间吗？', pron: 'kho du hong gon dai mai ka', scene: '要求实地看房', diff: '常用', tone: '礼貌', gender: 'female', tags: ['租房', '看房'] },
  { id: 8, cat: 'rent', thai: 'ใกล้BTSไหมคะ', cn: '离BTS近吗？', pron: 'klai bts mai ka', scene: '问交通是否方便', diff: '常用', tone: '日常', gender: 'female', tags: ['租房', '交通'] },
  { id: 9, cat: 'rent', thai: 'มีที่จอดรถไหมคะ', cn: '有停车位吗？', pron: 'mee thi chot rot mai ka', scene: '开车人士问停车', diff: '常用', tone: '日常', gender: 'female', tags: ['租房', '停车'] },
  { id: 10, cat: 'rent', thai: 'ห้องรวมเฟอร์นิเจอร์ไหมคะ', cn: '房间带家具吗？', pron: 'hong ruam foe-ni-choe mai ka', scene: '问是否含家具', diff: '进阶', tone: '日常', gender: 'female', tags: ['租房', '家具'] },
  { id: 11, cat: 'rent', thai: 'เช่าขั้นต่ำกี่เดือนคะ', cn: '最少租几个月？', pron: 'chao khan tom ki duean ka', scene: '问最短租期', diff: '常用', tone: '日常', gender: 'female', tags: ['租房', '租期'] },
  { id: 12, cat: 'rent', thai: 'วันไหนย้ายเข้าได้คะ', cn: '哪天可以搬进来？', pron: 'wan nai yai khao dai ka', scene: '确定入住日期', diff: '常用', tone: '日常', gender: 'female', tags: ['租房', '入住'] },
  { id: 13, cat: 'rent', thai: 'ต้องทำสัญญากี่เดือนคะ', cn: '要签几个月合同？', pron: 'tong tham sanya ki duean ka', scene: '询问合约期限', diff: '进阶', tone: '日常', gender: 'female', tags: ['租房', '合同'] },
  { id: 14, cat: 'rent', thai: 'มีห้องแบบสตูดิโอไหมคะ', cn: '有Studio（单间）吗？', pron: 'mee hong baep studio mai ka', scene: '问房型', diff: '进阶', tone: '日常', gender: 'female', tags: ['租房', '房型'] },
  { id: 15, cat: 'rent', thai: 'ลิฟต์อยู่ชั้นไหนคะ', cn: '电梯在几楼？', pron: 'lift yu chan nai ka', scene: '找电梯位置', diff: '入门', tone: '日常', gender: 'female', tags: ['租房', '电梯'] },

  // ===== Part 2: Grab打车 =====
  { id: 16, cat: 'grab', thai: 'สวัสดีค่ะ', cn: '你好', pron: 'sa-wat-di ka', scene: '上车跟司机打招呼', diff: '入门', tone: '礼貌', gender: 'female', tags: ['打车', '打招呼'] },
  { id: 17, cat: 'grab', thai: 'ไปที่นี่ค่ะ', cn: '去这个地方', pron: 'pai thi ni ka', scene: '给司机看地址或地图', diff: '入门', tone: '日常', gender: 'female', tags: ['打车', '目的地'] },
  { id: 18, cat: 'grab', thai: 'ใช้เวลาประมาณกี่นาทีคะ', cn: '大概要几分钟？', pron: 'chai we-la pra-man ki na-thi ka', scene: '问预估时间', diff: '常用', tone: '日常', gender: 'female', tags: ['打车', '时间'] },
  { id: 19, cat: 'grab', thai: 'รอสักครู่ได้ไหมคะ', cn: '可以等一下吗？', pron: 'ro sak khru dai mai ka', scene: '让司机等几分钟', diff: '常用', tone: '礼貌', gender: 'female', tags: ['打车', '等待'] },
  { id: 20, cat: 'grab', thai: 'ขับช้าหน่อยได้ไหมคะ', cn: '可以开慢一点吗？', pron: 'khap cha noi dai mai ka', scene: '觉得太快时提醒司机', diff: '常用', tone: '礼貌', gender: 'female', tags: ['打车', '安全'] },
  { id: 21, cat: 'grab', thai: 'ถึงแล้วบอกด้วยนะคะ', cn: '到了告诉我一声', pron: 'thueng laeo bok duai na ka', scene: '怕坐过站时说', diff: '常用', tone: '日常', gender: 'female', tags: ['打车', '提醒'] },
  { id: 22, cat: 'grab', thai: 'ไม่ต้องทอนค่ะ', cn: '不用找了', pron: 'mai tong thon ka', scene: '给整钱不用找零', diff: '常用', tone: '日常', gender: 'female', tags: ['打车', '付款'] },
  { id: 23, cat: 'grab', thai: 'เลี้ยวซ้ายค่ะ', cn: '左转', pron: 'liao sai ka', scene: '给司机指路', diff: '入门', tone: '日常', gender: 'female', tags: ['打车', '指路'] },
  { id: 24, cat: 'grab', thai: 'เลี้ยวขวาค่ะ', cn: '右转', pron: 'liao khwa ka', scene: '给司机指路', diff: '入门', tone: '日常', gender: 'female', tags: ['打车', '指路'] },
  { id: 25, cat: 'grab', thai: 'ตรงไปค่ะ', cn: '直走', pron: 'trong pai ka', scene: '给司机指路', diff: '入门', tone: '日常', gender: 'female', tags: ['打车', '指路'] },
  { id: 26, cat: 'grab', thai: 'จอดตรงนี้ได้เลยค่ะ', cn: '停这里就可以', pron: 'chot trong ni dai loei ka', scene: '到了告诉司机停车', diff: '常用', tone: '日常', gender: 'female', tags: ['打车', '停车'] },
  { id: 27, cat: 'grab', thai: 'ขอบคุณค่ะ', cn: '谢谢', pron: 'khop khun ka', scene: '下车时感谢司机', diff: '入门', tone: '礼貌', gender: 'female', tags: ['打车', '感谢'] },

  // ===== Part 3: 餐厅 =====
  { id: 28, cat: 'restaurant', thai: 'กี่ท่านคะ', cn: '几位？', pron: 'ki than ka', scene: '服务员问人数', diff: '入门', tone: '日常', gender: 'female', tags: ['餐厅', '入座'] },
  { id: 29, cat: 'restaurant', thai: 'สองคนค่ะ', cn: '两位', pron: 'song khon ka', scene: '回答人数', diff: '入门', tone: '日常', gender: 'female', tags: ['餐厅', '入座'] },
  { id: 30, cat: 'restaurant', thai: 'มีอะไรแนะนำไหมคะ', cn: '有什么推荐吗？', pron: 'mee a-rai nae-nam mai ka', scene: '让服务员推荐菜', diff: '常用', tone: '礼貌', gender: 'female', tags: ['餐厅', '推荐'] },
  { id: 31, cat: 'restaurant', thai: 'ขอเมนูค่ะ', cn: '请给我菜单', pron: 'kho menu ka', scene: '要菜单', diff: '入门', tone: '礼貌', gender: 'female', tags: ['餐厅', '点餐'] },
  { id: 32, cat: 'restaurant', thai: 'ไม่เผ็ดค่ะ', cn: '不要辣', pron: 'mai phet ka', scene: '点餐时说明口味', diff: '入门', tone: '日常', gender: 'female', tags: ['餐厅', '辣度'] },
  { id: 33, cat: 'restaurant', thai: 'เผ็ดน้อยค่ะ', cn: '微辣', pron: 'phet noi ka', scene: '点餐时说明辣度', diff: '入门', tone: '日常', gender: 'female', tags: ['餐厅', '辣度'] },
  { id: 34, cat: 'restaurant', thai: 'เผ็ดกลางค่ะ', cn: '中辣', pron: 'phet klang ka', scene: '点餐时说明辣度', diff: '常用', tone: '日常', gender: 'female', tags: ['餐厅', '辣度'] },
  { id: 35, cat: 'restaurant', thai: 'ขอส้มตำไก่ย่างค่ะ', cn: '要一份凉拌木瓜配烤鸡', pron: 'kho som tam kai yang ka', scene: '点经典泰式菜品', diff: '进阶', tone: '日常', gender: 'female', tags: ['餐厅', '点菜'] },
  { id: 36, cat: 'restaurant', thai: 'ขอข้าวเหนียว1ห่อค่ะ', cn: '要一份糯米饭', pron: 'kho khao niao nueng ho ka', scene: '点主食', diff: '常用', tone: '日常', gender: 'female', tags: ['餐厅', '点菜'] },
  { id: 37, cat: 'restaurant', thai: 'เช็คบิลด้วยค่ะ', cn: '买单', pron: 'chek bil duai ka', scene: '吃完要结账', diff: '入门', tone: '日常', gender: 'female', tags: ['餐厅', '买单'] },
  { id: 38, cat: 'restaurant', thai: 'ขอกล่องด้วยค่ะ', cn: '请给我打包盒', pron: 'kho klong duai ka', scene: '吃不完要打包', diff: '常用', tone: '日常', gender: 'female', tags: ['餐厅', '打包'] },
  { id: 39, cat: 'restaurant', thai: 'อร่อยมากค่ะ', cn: '很好吃', pron: 'a-roi mak ka', scene: '夸赞食物好吃', diff: '入门', tone: '可爱', gender: 'female', tags: ['餐厅', '夸赞'] },
  { id: 40, cat: 'restaurant', thai: 'ขอน้ำเปล่าค่ะ', cn: '要一杯白水', pron: 'kho nam plao ka', scene: '要免费饮用水', diff: '入门', tone: '日常', gender: 'female', tags: ['餐厅', '饮料'] },
  { id: 41, cat: 'restaurant', thai: 'ไม่ใส่ผงชูรสค่ะ', cn: '不要加味精', pron: 'mai sai phong chu rot ka', scene: '要求不加味精', diff: '进阶', tone: '日常', gender: 'female', tags: ['餐厅', '口味'] },

  // ===== Part 4: 7-11便利店 =====
  { id: 42, cat: 'seven11', thai: 'อุ่นให้หน่อยค่ะ', cn: '请帮我加热', pron: 'un hai noi ka', scene: '买便当让店员加热', diff: '常用', tone: '日常', gender: 'female', tags: ['便利店', '加热'] },
  { id: 43, cat: 'seven11', thai: 'ขอถุงค่ะ', cn: '要个袋子', pron: 'kho thung ka', scene: '买东西要袋子', diff: '入门', tone: '日常', gender: 'female', tags: ['便利店', '袋子'] },
  { id: 44, cat: 'seven11', thai: 'ไม่ต้องถุงค่ะ', cn: '不用袋子', pron: 'mai tong thung ka', scene: '环保不需要袋子', diff: '入门', tone: '日常', gender: 'female', tags: ['便利店', '环保'] },
  { id: 45, cat: 'seven11', thai: 'มีstrawไหมคะ', cn: '有吸管吗？', pron: 'mee straw mai ka', scene: '买饮料要吸管', diff: '入门', tone: '日常', gender: 'female', tags: ['便利店', '吸管'] },
  { id: 46, cat: 'seven11', thai: 'เก็บเงินได้ไหมคะ', cn: '可以换零钱吗？', pron: 'kep ngoen dai mai ka', scene: '需要换零钱', diff: '常用', tone: '日常', gender: 'female', tags: ['便利店', '零钱'] },
  { id: 47, cat: 'seven11', thai: 'ขอrefundค่ะ', cn: '我要退货', pron: 'kho refund ka', scene: '需要退换商品', diff: '进阶', tone: '日常', gender: 'female', tags: ['便利店', '退货'] },
  { id: 48, cat: 'seven11', thai: 'จ่ายผ่านQRได้ไหมคะ', cn: '可以扫码支付吗？', pron: 'chai phaon QR dai mai ka', scene: '问能否扫码付款', diff: '常用', tone: '日常', gender: 'female', tags: ['便利店', '支付'] },
  { id: 49, cat: 'seven11', thai: 'มีบิลใบเลยค่ะ', cn: '请给我小票', pron: 'mee bil bai loei ka', scene: '索要收据', diff: '常用', tone: '礼貌', gender: 'female', tags: ['便利店', '小票'] },

  // ===== Part 5: 按摩 =====
  { id: 50, cat: 'massage', thai: 'ขอนวดไทยค่ะ', cn: '我要泰式按摩', pron: 'kho nuat thai ka', scene: '选择按摩类型', diff: '入门', tone: '日常', gender: 'female', tags: ['按摩', '类型'] },
  { id: 51, cat: 'massage', thai: 'ขอนวดเท้าค่ะ', cn: '我要足底按摩', pron: 'kho nuat thao ka', scene: '选择按摩类型', diff: '入门', tone: '日常', gender: 'female', tags: ['按摩', '类型'] },
  { id: 52, cat: 'massage', thai: 'ขอนวดน้ำมันค่ะ', cn: '我要精油按摩', pron: 'kho nuat nam man ka', scene: '选择按摩类型', diff: '常用', tone: '日常', gender: 'female', tags: ['按摩', '类型'] },
  { id: 53, cat: 'massage', thai: 'นวด1ชั่วโมงค่ะ', cn: '按摩一个小时', pron: 'nuat nueng chua-mon ka', scene: '选择时长', diff: '入门', tone: '日常', gender: 'female', tags: ['按摩', '时长'] },
  { id: 54, cat: 'massage', thai: 'เบาหน่อยค่ะ', cn: '轻一点', pron: 'bao noi ka', scene: '力度太大时说', diff: '常用', tone: '日常', gender: 'female', tags: ['按摩', '力度'] },
  { id: 55, cat: 'massage', thai: 'หนักหน่อยค่ะ', cn: '重一点', pron: 'nak noi ka', scene: '力度不够时说', diff: '常用', tone: '日常', gender: 'female', tags: ['按摩', '力度'] },
  { id: 56, cat: 'massage', thai: 'ปวดตรงนี้ค่ะ', cn: '这里疼', pron: 'puat trong ni ka', scene: '告诉技师哪里酸痛', diff: '常用', tone: '日常', gender: 'female', tags: ['按摩', '部位'] },
  { id: 57, cat: 'massage', thai: 'เพิ่มเวลาอีกค่ะ', cn: '加钟', pron: 'phoem we-la ik ka', scene: '想延长按摩时间', diff: '进阶', tone: '日常', gender: 'female', tags: ['按摩', '加钟'] },

  // ===== Part 6: 看病 =====
  { id: 58, cat: 'doctor', thai: 'ไม่สบายค่ะ', cn: '我不舒服', pron: 'mai sa-bai ka', scene: '告诉医生身体不适', diff: '入门', tone: '日常', gender: 'female', tags: ['看病', '症状'] },
  { id: 59, cat: 'doctor', thai: 'มีไข้ค่ะ', cn: '我发烧了', pron: 'mee khai ka', scene: '描述症状', diff: '入门', tone: '日常', gender: 'female', tags: ['看病', '发烧'] },
  { id: 60, cat: 'doctor', thai: 'ปวดหัวค่ะ', cn: '头痛', pron: 'puat hua ka', scene: '描述症状', diff: '入门', tone: '日常', gender: 'female', tags: ['看病', '头痛'] },
  { id: 61, cat: 'doctor', thai: 'ปวดท้องค่ะ', cn: '肚子疼', pron: 'puat thong ka', scene: '描述症状', diff: '入门', tone: '日常', gender: 'female', tags: ['看病', '肚子疼'] },
  { id: 62, cat: 'doctor', thai: 'ไอค่ะ', cn: '咳嗽', pron: 'ai ka', scene: '描述症状', diff: '入门', tone: '日常', gender: 'female', tags: ['看病', '咳嗽'] },
  { id: 63, cat: 'doctor', thai: 'เจ็บคอค่ะ', cn: '嗓子疼', pron: 'chip kho ka', scene: '描述症状', diff: '常用', tone: '日常', gender: 'female', tags: ['看病', '嗓子'] },
  { id: 64, cat: 'doctor', thai: 'ท้องเสียค่ะ', cn: '拉肚子', pron: 'thong sia ka', scene: '描述症状', diff: '常用', tone: '日常', gender: 'female', tags: ['看病', '腹泻'] },
  { id: 65, cat: 'doctor', thai: 'คันตรงนี้ค่ะ', cn: '这里痒', pron: 'khan trong ni ka', scene: '皮肤过敏时指位置', diff: '进阶', tone: '日常', gender: 'female', tags: ['看病', '过敏'] },
  { id: 66, cat: 'doctor', thai: 'แพ้ยาค่ะ', cn: '我对药物过敏', pron: 'phae ya ka', scene: '告知医生药物过敏', diff: '进阶', tone: '日常', gender: 'female', tags: ['看病', '过敏'] },
  { id: 67, cat: 'doctor', thai: 'กินยายังไงคะ', cn: '药怎么吃？', pron: 'kin ya yang-ngai ka', scene: '问用药方法', diff: '常用', tone: '礼貌', gender: 'female', tags: ['看病', '用药'] },

  // ===== Part 7: 恋爱 =====
  { id: 68, cat: 'love', thai: 'ชอบคุณค่ะ', cn: '我喜欢你', pron: 'chop khun ka', scene: '表白时说', diff: '入门', tone: '温柔', gender: 'female', tags: ['恋爱', '表白'] },
  { id: 69, cat: 'love', thai: 'รักคุณค่ะ', cn: '我爱你', pron: 'rak khun ka', scene: '对恋人表达爱意', diff: '入门', tone: '温柔', gender: 'female', tags: ['恋爱', '表白'] },
  { id: 70, cat: 'love', thai: 'คิดถึงคุณค่ะ', cn: '想你了', pron: 'khit thueng khun ka', scene: '想念对方时说', diff: '常用', tone: '温柔', gender: 'female', tags: ['恋爱', '想念'] },
  { id: 71, cat: 'love', thai: 'อยากเจอคุณค่ะ', cn: '想见你', pron: 'yak choe khun ka', scene: '想约对方见面', diff: '常用', tone: '温柔', gender: 'female', tags: ['恋爱', '约会'] },
  { id: 72, cat: 'love', thai: 'น่ารักจังค่ะ', cn: '好可爱啊', pron: 'na-rak chang ka', scene: '夸对方可爱', diff: '入门', tone: '可爱', gender: 'female', tags: ['恋爱', '夸赞'] },
  { id: 73, cat: 'love', thai: 'คุณหล่อมากค่ะ', cn: '你好帅', pron: 'khun lo mak ka', scene: '夸男生帅气', diff: '常用', tone: '可爱', gender: 'female', tags: ['恋爱', '夸赞'] },
  { id: 74, cat: 'love', thai: 'ออกเดทกันไหมคะ', cn: '要不要去约会？', pron: 'ok det kan mai ka', scene: '约对方出去', diff: '进阶', tone: '温柔', gender: 'female', tags: ['恋爱', '约会'] },
  { id: 75, cat: 'love', thai: 'เป็นแฟนกันไหมคะ', cn: '要不要在一起？', pron: 'pen faen kan mai ka', scene: '正式确定关系', diff: '进阶', tone: '温柔', gender: 'female', tags: ['恋爱', '表白'] },
  { id: 76, cat: 'love', thai: 'ยอมรับไม่ได้ค่ะ', cn: '我不能接受', pron: 'yom rap mai dai ka', scene: '拒绝表白', diff: '进阶', tone: '日常', gender: 'female', tags: ['恋爱', '拒绝'] },
  { id: 77, cat: 'love', thai: 'เราเป็นเพื่อนกันก่อนนะคะ', cn: '我们先做朋友吧', pron: 'rao pen phuean kan gon na ka', scene: '委婉拒绝', diff: '进阶', tone: '温柔', gender: 'female', tags: ['恋爱', '拒绝'] },

  // ===== Part 8: 交友 =====
  { id: 78, cat: 'friend', thai: 'ขอLINEคุณได้ไหมคะ', cn: '可以加你的LINE吗？', pron: 'kho LINE khun dai mai ka', scene: '想保持联系加社交账号', diff: '常用', tone: '礼貌', gender: 'female', tags: ['交友', 'LINE'] },
  { id: 79, cat: 'friend', thai: 'แอดผมกลับได้เลยค่ะ', cn: '可以加我回去哦', pron: 'aet klap dai loei ka', scene: '同意互加好友', diff: '常用', tone: '可爱', gender: 'female', tags: ['交友', 'LINE'] },
  { id: 80, cat: 'friend', thai: 'คุณอายุเท่าไหร่คะ', cn: '你多大了？', pron: 'khun a-yu thao rai ka', scene: '认识新朋友时问年龄', diff: '入门', tone: '日常', gender: 'female', tags: ['交友', '年龄'] },
  { id: 81, cat: 'friend', thai: 'คุณทำงานอะไรคะ', cn: '你是做什么工作的？', pron: 'khun tham-ngan a-rai ka', scene: '问职业', diff: '入门', tone: '日常', gender: 'female', tags: ['交友', '职业'] },
  { id: 82, cat: 'friend', thai: 'มาจากประเทศไหนคะ', cn: '你来自哪个国家？', pron: 'ma jak pra-thet nai ka', scene: '问国籍', diff: '入门', tone: '日常', gender: 'female', tags: ['交友', '国籍'] },
  { id: 83, cat: 'friend', thai: 'อยู่ไทยนานหรือยังคะ', cn: '在泰国待很久了吗？', pron: 'yu thai nan rue yang ka', scene: '问在泰时间', diff: '常用', tone: '日常', gender: 'female', tags: ['交友', '闲聊'] },
  { id: 84, cat: 'friend', thai: 'ไปเที่ยวด้วยกันไหมคะ', cn: '一起去玩吗？', pron: 'pai thio duai kan mai ka', scene: '约新朋友一起出去玩', diff: '常用', tone: '可爱', gender: 'female', tags: ['交友', '约玩'] },
  { id: 85, cat: 'friend', thai: 'คุณพูดไทยเก่งมากค่ะ', cn: '你泰语说得很好', pron: 'khun phut thai keng mak ka', scene: '夸赞对方泰语好', diff: '常用', tone: '可爱', gender: 'female', tags: ['交友', '夸赞'] },

  // ===== Part 9: 购物 =====
  { id: 86, cat: 'shopping', thai: 'ราคาเท่าไหร่คะ', cn: '多少钱？', pron: 'rakha thao rai ka', scene: '问价格', diff: '入门', tone: '日常', gender: 'female', tags: ['购物', '问价'] },
  { id: 87, cat: 'shopping', thai: 'ลดหน่อยได้ไหมคะ', cn: '可以便宜点吗？', pron: 'lot noi dai mai ka', scene: '砍价', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '砍价'] },
  { id: 88, cat: 'shopping', thai: 'ราคาพอไหวไหมคะ', cn: '价格还能再低吗？', pron: 'rakha pho wai mai ka', scene: '进一步砍价', diff: '进阶', tone: '日常', gender: 'female', tags: ['购物', '砍价'] },
  { id: 89, cat: 'shopping', thai: 'ขอลองใส่ดูได้ไหมคะ', cn: '可以试穿吗？', pron: 'kho long sai du dai mai ka', scene: '买衣服时试穿', diff: '常用', tone: '礼貌', gender: 'female', tags: ['购物', '试穿'] },
  { id: 90, cat: 'shopping', thai: 'มีไซส์ใหญ่กว่าไหมคะ', cn: '有大一码的吗？', pron: 'mee size yai kwa mai ka', scene: '要更大尺码', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '尺码'] },
  { id: 91, cat: 'shopping', thai: 'มีสีอื่นไหมคะ', cn: '有别的颜色吗？', pron: 'mee si uen mai ka', scene: '问其他颜色', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '颜色'] },
  { id: 92, cat: 'shopping', thai: 'เอาอันนี้ค่ะ', cn: '要这个', pron: 'ao an ni ka', scene: '决定购买', diff: '入门', tone: '日常', gender: 'female', tags: ['购物', '购买'] },
  { id: 93, cat: 'shopping', thai: 'ไม่เอาค่ะ ขอบคุณค่ะ', cn: '不要了，谢谢', pron: 'mai ao ka khop khun ka', scene: '礼貌拒绝', diff: '入门', tone: '礼貌', gender: 'female', tags: ['购物', '拒绝'] },
  { id: 94, cat: 'shopping', thai: 'มีโปรไหมคะ', cn: '有促销吗？', pron: 'mee pro mai ka', scene: '问折扣活动', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '折扣'] },
  { id: 95, cat: 'shopping', thai: 'ใช้บัตรเครดิตได้ไหมคะ', cn: '可以刷信用卡吗？', pron: 'chai bat credit dai mai ka', scene: '问支付方式', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '支付'] },

  // ===== Part 10.1: 100句·日常用语 =====
  { id: 96, cat: 'daily', thai: 'สวัสดีค่ะ', cn: '你好', pron: 'sa-wat-di ka', scene: '日常打招呼', diff: '入门', tone: '礼貌', gender: 'female', tags: ['日常', '打招呼'] },
  { id: 97, cat: 'daily', thai: 'สบายดีไหมคะ', cn: '你还好吗？', pron: 'sa-bai di mai ka', scene: '关心问候', diff: '入门', tone: '温柔', gender: 'female', tags: ['日常', '问候'] },
  { id: 98, cat: 'daily', thai: 'ขอบคุณค่ะ', cn: '谢谢', pron: 'khop khun ka', scene: '表示感谢', diff: '入门', tone: '礼貌', gender: 'female', tags: ['日常', '感谢'] },
  { id: 99, cat: 'daily', thai: 'ขอโทษค่ะ', cn: '对不起/不好意思', pron: 'kho thot ka', scene: '道歉或借过', diff: '入门', tone: '礼貌', gender: 'female', tags: ['日常', '道歉'] },
  { id: 100, cat: 'daily', thai: 'ไม่เป็นไรค่ะ', cn: '没关系', pron: 'mai pen rai ka', scene: '回应道歉', diff: '入门', tone: '温柔', gender: 'female', tags: ['日常', '回应'] },
  { id: 101, cat: 'daily', thai: 'ใช่ค่ะ', cn: '是的/对', pron: 'chai ka', scene: '肯定回答', diff: '入门', tone: '日常', gender: 'female', tags: ['日常', '肯定'] },
  { id: 102, cat: 'daily', thai: 'ไม่ใช่ค่ะ', cn: '不是', pron: 'mai chai ka', scene: '否定回答', diff: '入门', tone: '日常', gender: 'female', tags: ['日常', '否定'] },
  { id: 103, cat: 'daily', thai: 'ไม่ทราบค่ะ', cn: '不知道', pron: 'mai sap ka', scene: '表示不确定', diff: '入门', tone: '礼貌', gender: 'female', tags: ['日常', '不确定'] },
  { id: 104, cat: 'daily', thai: 'ช่ายค่ะ ฉันเข้าใจแล้ว', cn: '是的，我明白了', pron: 'chai ka chan khao chai laeo', scene: '表示理解了对方意思', diff: '常用', tone: '日常', gender: 'female', tags: ['日常', '理解'] },
  { id: 105, cat: 'daily', thai: 'พูดช้าลงหน่อยได้ไหมคะ', cn: '可以说慢一点吗？', pron: 'phut cha long noi dai mai ka', scene: '对方说太快时请求放慢', diff: '常用', tone: '礼貌', gender: 'female', tags: ['日常', '沟通'] },
  { id: 106, cat: 'daily', thai: 'พูดอีกครั้งได้ไหมคะ', cn: '可以再说一遍吗？', pron: 'phut ik krang dai mai ka', scene: '没听清请求重复', diff: '常用', tone: '礼貌', gender: 'female', tags: ['日常', '沟通'] },
  { id: 107, cat: 'daily', thai: 'ฉันไม่เข้าใจค่ะ', cn: '我不明白', pron: 'chan mai khao chai ka', scene: '表示听不懂', diff: '常用', tone: '日常', gender: 'female', tags: ['日常', '沟通'] },
  { id: 108, cat: 'daily', thai: 'ห้องน้ำอยู่ที่ไหนคะ', cn: '洗手间在哪里？', pron: 'hong nam yu thi nai ka', scene: '找厕所', diff: '入门', tone: '日常', gender: 'female', tags: ['日常', '问路'] },
  { id: 109, cat: 'daily', thai: 'โทรศัพท์ฉันได้เลยค่ะ', cn: '可以打我电话', pron: 'tho-ra-sap chan dai loei ka', scene: '留电话给对方', diff: '常用', tone: '日常', gender: 'female', tags: ['日常', '联系'] },
  { id: 110, cat: 'daily', thai: 'ขอเวลาคิดสักครู่ค่ะ', cn: '给我一点时间想想', pron: 'kho we-la khit sak khru ka', scene: '需要考虑时说', diff: '常用', tone: '礼貌', gender: 'female', tags: ['日常', '考虑'] },
  { id: 111, cat: 'daily', thai: 'วันนี้อากาศดีจังค่ะ', cn: '今天天气真好', pron: 'wan ni a-kat di chang ka', scene: '闲聊天气', diff: '入门', tone: '可爱', gender: 'female', tags: ['日常', '天气'] },
  { id: 112, cat: 'daily', thai: 'ฉันรู้สึกเหนื่อยค่ะ', cn: '我觉得好累', pron: 'chan ru-suek nueay ka', scene: '表达疲惫', diff: '常用', tone: '日常', gender: 'female', tags: ['日常', '感受'] },
  { id: 113, cat: 'daily', thai: 'ฉันสบายดีค่ะ', cn: '我很好', pron: 'chan sa-bai di ka', scene: '回应关心', diff: '入门', tone: '日常', gender: 'female', tags: ['日常', '感受'] },
  { id: 114, cat: 'daily', thai: 'ฝันดีนะคะ', cn: '晚安', pron: 'fan di na ka', scene: '睡前道别', diff: '入门', tone: '温柔', gender: 'female', tags: ['日常', '晚安'] },
  { id: 115, cat: 'daily', thai: 'แล้วเจอกันใหม่ค่ะ', cn: '再见/回头见', pron: 'laeo choe kan mai ka', scene: '告别', diff: '入门', tone: '日常', gender: 'female', tags: ['日常', '告别'] },

  // ===== Part 10.2: 100句·购物用语 =====
  { id: 116, cat: 'daily-shop', thai: 'เปิดกี่โมงคะ', cn: '几点开门？', pron: 'poet ki mong ka', scene: '问营业时间', diff: '入门', tone: '日常', gender: 'female', tags: ['购物', '时间'] },
  { id: 117, cat: 'daily-shop', thai: 'ปิดกี่โมงคะ', cn: '几点关门？', pron: 'pit ki mong ka', scene: '问打烊时间', diff: '入门', tone: '日常', gender: 'female', tags: ['购物', '时间'] },
  { id: 118, cat: 'daily-shop', thai: 'ดูของก่อนได้ไหมคะ', cn: '可以先看看吗？', pron: 'du khong gon dai mai ka', scene: '逛店时先看看', diff: '入门', tone: '礼貌', gender: 'female', tags: ['购物', '看看'] },
  { id: 119, cat: 'daily-shop', thai: 'อันนี้ราคาเท่าไหร่คะ', cn: '这个多少钱？', pron: 'an ni rakha thao rai ka', scene: '问某件商品价格', diff: '入门', tone: '日常', gender: 'female', tags: ['购物', '问价'] },
  { id: 120, cat: 'daily-shop', thai: 'แพงไปค่ะ', cn: '太贵了', pron: 'phaeng pai ka', scene: '嫌价格高', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '砍价'] },
  { id: 121, cat: 'daily-shop', thai: 'ถูกกว่านี้มีไหมคะ', cn: '有更便宜的吗？', pron: 'thuk kwa ni mee mai ka', scene: '找更便宜的', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '砍价'] },
  { id: 122, cat: 'daily-shop', thai: 'รวมแล้วเท่าไหร่คะ', cn: '总共多少钱？', pron: 'ruam laeo thao rai ka', scene: '问总价', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '总价'] },
  { id: 123, cat: 'daily-shop', thai: 'มีของแถมไหมคะ', cn: '有赠品吗？', pron: 'mee khong thaem mai ka', scene: '问是否送赠品', diff: '常用', tone: '可爱', gender: 'female', tags: ['购物', '赠品'] },
  { id: 124, cat: 'daily-shop', thai: 'ส่งฟรีไหมคะ', cn: '包邮吗？', pron: 'song fri mai ka', scene: '网购问运费', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '运费'] },
  { id: 125, cat: 'daily-shop', thai: 'เปลี่ยนของได้ไหมคะ', cn: '可以换货吗？', pron: 'pliang khong dai mai ka', scene: '买回去想换', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '换货'] },
  { id: 126, cat: 'daily-shop', thai: 'คืนของได้ไหมคะ', cn: '可以退货吗？', pron: 'khuen khong dai mai ka', scene: '想退货', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '退货'] },
  { id: 127, cat: 'daily-shop', thai: 'มีบิลให้ด้วยค่ะ', cn: '请给我收据', pron: 'mee bil hai duai ka', scene: '要收据', diff: '常用', tone: '礼貌', gender: 'female', tags: ['购物', '收据'] },
  { id: 128, cat: 'daily-shop', thai: 'ใช้เงินสดค่ะ', cn: '我用现金', pron: 'chai ngoen sot ka', scene: '选择支付方式', diff: '入门', tone: '日常', gender: 'female', tags: ['购物', '支付'] },
  { id: 129, cat: 'daily-shop', thai: 'ห่อของให้หน่อยค่ะ', cn: '请帮我包起来', pron: 'hop khong hai noi ka', scene: '决定买了让店员包装', diff: '常用', tone: '礼貌', gender: 'female', tags: ['购物', '包装'] },
  { id: 130, cat: 'daily-shop', thai: 'มีใหม่ไหมคะ', cn: '有新的吗？', pron: 'mee mai mai ka', scene: '要全新未拆封的', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '新品'] },
  { id: 131, cat: 'daily-shop', thai: 'เอาแบบนี้ค่ะ', cn: '要这种', pron: 'ao baep ni ka', scene: '指定款式', diff: '入门', tone: '日常', gender: 'female', tags: ['购物', '选择'] },
  { id: 132, cat: 'daily-shop', thai: 'มีสีดำไหมคะ', cn: '有黑色的吗？', pron: 'mee si dam mai ka', scene: '问特定颜色', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '颜色'] },
  { id: 133, cat: 'daily-shop', thai: 'มีขนาดเล็กกว่าไหมคะ', cn: '有小一号的吗？', pron: 'mee kha-nat lek kwa mai ka', scene: '要更小尺码', diff: '常用', tone: '日常', gender: 'female', tags: ['购物', '尺码'] },
  { id: 134, cat: 'daily-shop', thai: 'ขอดูอันนั้นได้ไหมคะ', cn: '可以看看那个吗？', pron: 'kho du an nan dai mai ka', scene: '让店员拿商品看', diff: '常用', tone: '礼貌', gender: 'female', tags: ['购物', '看货'] },
  { id: 135, cat: 'daily-shop', thai: 'ลดได้สูงสุดเท่าไหร่คะ', cn: '最多能便宜多少？', pron: 'lot dai sut thao rai ka', scene: '问最大折扣', diff: '进阶', tone: '日常', gender: 'female', tags: ['购物', '砍价'] },

  // ===== Part 10.3: 100句·餐饮用语 =====
  { id: 136, cat: 'daily-eat', thai: 'กินอะไรดีคะ', cn: '吃什么好呢？', pron: 'kin a-rai di ka', scene: '不知道吃什么时说', diff: '入门', tone: '日常', gender: 'female', tags: ['餐饮', '选择'] },
  { id: 137, cat: 'daily-eat', thai: 'ไปกินข้าวกันไหมคะ', cn: '一起去吃饭吗？', pron: 'pai kin khao kan mai ka', scene: '约人吃饭', diff: '入门', tone: '可爱', gender: 'female', tags: ['餐饮', '约饭'] },
  { id: 138, cat: 'daily-eat', thai: 'ร้านนี้อร่อยไหมคะ', cn: '这家店好吃吗？', pron: 'ran ni a-roi mai ka', scene: '问餐厅好不好吃', diff: '常用', tone: '日常', gender: 'female', tags: ['餐饮', '推荐'] },
  { id: 139, cat: 'daily-eat', thai: 'ขอเมนูด้วยค่ะ', cn: '请给我菜单', pron: 'kho menu duai ka', scene: '入座后要菜单', diff: '入门', tone: '礼貌', gender: 'female', tags: ['餐饮', '点餐'] },
  { id: 140, cat: 'daily-eat', thai: 'ขอสั่งอาหารค่ะ', cn: '我要点餐', pron: 'kho sang a-han ka', scene: '叫服务员点餐', diff: '入门', tone: '日常', gender: 'female', tags: ['餐饮', '点餐'] },
  { id: 141, cat: 'daily-eat', thai: 'ขอผัดไทยค่ะ', cn: '要一份泰式炒粉', pron: 'kho phat thai ka', scene: '点经典泰菜', diff: '常用', tone: '日常', gender: 'female', tags: ['餐饮', '点菜'] },
  { id: 142, cat: 'daily-eat', thai: 'ขอต้มยำกุ้งค่ะ', cn: '要一份冬阴功汤', pron: 'kho tom yam kung ka', scene: '点经典泰菜', diff: '常用', tone: '日常', gender: 'female', tags: ['餐饮', '点菜'] },
  { id: 143, cat: 'daily-eat', thai: 'ไม่ใส่ถั่วค่ะ', cn: '不要加花生', pron: 'mai sai thua ka', scene: '说明忌口', diff: '进阶', tone: '日常', gender: 'female', tags: ['餐饮', '忌口'] },
  { id: 144, cat: 'daily-eat', thai: 'หวานน้อยค่ะ', cn: '少糖', pron: 'wan noi ka', scene: '买奶茶时说', diff: '常用', tone: '日常', gender: 'female', tags: ['餐饮', '口味'] },
  { id: 145, cat: 'daily-eat', thai: 'เย็นค่ะ', cn: '要冰的', pron: 'yen ka', scene: '选冷饮', diff: '入门', tone: '日常', gender: 'female', tags: ['餐饮', '饮料'] },
  { id: 146, cat: 'daily-eat', thai: 'ร้อนค่ะ', cn: '要热的', pron: 'ron ka', scene: '选热饮', diff: '入门', tone: '日常', gender: 'female', tags: ['餐饮', '饮料'] },
  { id: 147, cat: 'daily-eat', thai: 'อร่อยที่สุดค่ะ', cn: '太好吃了', pron: 'a-roi thi sut ka', scene: '强烈夸赞食物', diff: '常用', tone: '可爱', gender: 'female', tags: ['餐饮', '夸赞'] },
  { id: 148, cat: 'daily-eat', thai: 'อิ่มแล้วค่ะ', cn: '我吃饱了', pron: 'im laeo ka', scene: '表示吃饱', diff: '入门', tone: '日常', gender: 'female', tags: ['餐饮', '吃饱'] },
  { id: 149, cat: 'daily-eat', thai: 'ยังไม่อิ่มค่ะ', cn: '还没吃饱', pron: 'yang mai im ka', scene: '表示没吃饱', diff: '常用', tone: '日常', gender: 'female', tags: ['餐饮', '没饱'] },
  { id: 150, cat: 'daily-eat', thai: 'ขอช้อนกับส้อมค่ะ', cn: '请给我勺子和叉子', pron: 'kho chon kap som ka', scene: '要餐具', diff: '常用', tone: '礼貌', gender: 'female', tags: ['餐饮', '餐具'] },
  { id: 151, cat: 'daily-eat', thai: 'ขอน้ำจืดค่ะ', cn: '要白水', pron: 'kho nam chuet ka', scene: '要饮用水', diff: '入门', tone: '日常', gender: 'female', tags: ['餐饮', '饮料'] },
  { id: 152, cat: 'daily-eat', thai: 'ขอทิพแอลกอฮอล์ไม่มีค่ะ', cn: '要无酒精饮料', pron: 'kho thip ael kor-hol mai mee ka', scene: '不喝酒时要无酒精', diff: '进阶', tone: '日常', gender: 'female', tags: ['餐饮', '饮料'] },
  { id: 153, cat: 'daily-eat', thai: 'กลับบ้านดึกค่ะ ขอกล่องด้วย', cn: '回去晚了，请打包', pron: 'klap ban duek ka kho klong duai', scene: '打包剩菜', diff: '常用', tone: '日常', gender: 'female', tags: ['餐饮', '打包'] },
  { id: 154, cat: 'daily-eat', thai: 'แยกบิลได้ไหมคะ', cn: '可以分开结账吗？', pron: 'yaek bil dai mai ka', scene: 'AA制各自付', diff: '进阶', tone: '日常', gender: 'female', tags: ['餐饮', '结账'] },
  { id: 155, cat: 'daily-eat', thai: 'วันนี้เลี้ยงค่ะ', cn: '今天我请客', pron: 'wan ni liang ka', scene: '主动请客', diff: '常用', tone: '可爱', gender: 'female', tags: ['餐饮', '请客'] },

  // ===== Part 10.4: 100句·出行用语 =====
  { id: 156, cat: 'daily-go', thai: 'สนามบินอยู่ที่ไหนคะ', cn: '机场在哪里？', pron: 'sa-nam-bin yu thi nai ka', scene: '问机场方向', diff: '入门', tone: '日常', gender: 'female', tags: ['出行', '机场'] },
  { id: 157, cat: 'daily-go', thai: 'ไปสนามบินกี่โมงคะ', cn: '去机场要几点的？', pron: 'pai sa-nam-bin ki mong ka', scene: '规划出发时间', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '机场'] },
  { id: 158, cat: 'daily-go', thai: 'ขอเรียกแท็กซี่ค่ะ', cn: '帮我叫一辆出租车', pron: 'kho riaek taxi ka', scene: '让酒店叫车', diff: '常用', tone: '礼貌', gender: 'female', tags: ['出行', '打车'] },
  { id: 159, cat: 'daily-go', thai: 'ไปถนนขอวังค่ะ', cn: '去考山路', pron: 'pai thanon khao wang ka', scene: '告诉司机目的地', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '目的地'] },
  { id: 160, cat: 'daily-go', thai: 'รถไฟใต้ดินสถานีไหนคะ', cn: '地铁哪个站？', pron: 'rot fai tai din sa-tha-ni nai ka', scene: '问地铁站', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '地铁'] },
  { id: 161, cat: 'daily-go', thai: 'ต้องเปลี่ยนขบวนไหมคะ', cn: '需要换乘吗？', pron: 'tong pliang khon mai ka', scene: '问是否需要转车', diff: '进阶', tone: '日常', gender: 'female', tags: ['出行', '换乘'] },
  { id: 162, cat: 'daily-go', thai: 'ตั๋วราคาเท่าไหร่คะ', cn: '票多少钱？', pron: 'tua rakha thao rai ka', scene: '问票价', diff: '入门', tone: '日常', gender: 'female', tags: ['出行', '票价'] },
  { id: 163, cat: 'daily-go', thai: 'ขอตั๋ว2ใบค่ะ', cn: '要两张票', pron: 'kho tua song bai ka', scene: '买车票', diff: '入门', tone: '日常', gender: 'female', tags: ['出行', '买票'] },
  { id: 164, cat: 'daily-go', thai: 'รถออกกี่โมงคะ', cn: '车几点出发？', pron: 'rot ok ki mong ka', scene: '问发车时间', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '时间'] },
  { id: 165, cat: 'daily-go', thai: 'ใช้เวลากี่ชั่วโมงคะ', cn: '要几个小时？', pron: 'chai we-la ki chua-mong ka', scene: '问路程时间', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '时间'] },
  { id: 166, cat: 'daily-go', thai: 'โรงแรมอยู่ไกลไหมคะ', cn: '酒店远吗？', pron: 'rong-raem yu klai mai ka', scene: '问酒店距离', diff: '入门', tone: '日常', gender: 'female', tags: ['出行', '酒店'] },
  { id: 167, cat: 'daily-go', thai: 'ขอcheck-inค่ะ', cn: '我要办理入住', pron: 'kho check-in ka', scene: '酒店前台办理入住', diff: '常用', tone: '礼貌', gender: 'female', tags: ['出行', '酒店'] },
  { id: 168, cat: 'daily-go', thai: 'ขอcheck-outค่ะ', cn: '我要退房', pron: 'kho check-out ka', scene: '酒店前台退房', diff: '常用', tone: '礼貌', gender: 'female', tags: ['出行', '酒店'] },
  { id: 169, cat: 'daily-go', thai: 'มีห้องว่างไหมคะ', cn: '有空房吗？', pron: 'mee hong wang mai ka', scene: '到酒店问是否有房', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '酒店'] },
  { id: 170, cat: 'daily-go', thai: 'Wi-Fiรหัสอะไรคะ', cn: 'WiFi密码是多少？', pron: 'wifi ra-hat a-rai ka', scene: '问酒店WiFi密码', diff: '入门', tone: '日常', gender: 'female', tags: ['出行', 'WiFi'] },
  { id: 171, cat: 'daily-go', thai: 'ขอแผนที่หน่อยค่ะ', cn: '请给我地图', pron: 'kho phaen-thi noi ka', scene: '要酒店或游客中心地图', diff: '常用', tone: '礼貌', gender: 'female', tags: ['出行', '地图'] },
  { id: 172, cat: 'daily-go', thai: 'ไปตรงนี้เลยค่ะ', cn: '一直走这条路', pron: 'pai trong ni loei ka', scene: '给别人或司机指方向', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '指路'] },
  { id: 173, cat: 'daily-go', thai: 'อยู่ใกล้ๆเองค่ะ', cn: '就在附近', pron: 'yu klai klai eng ka', scene: '描述距离很近', diff: '常用', tone: '日常', gender: 'female', tags: ['出行', '距离'] },
  { id: 174, cat: 'daily-go', thai: 'ข้ามถนนแล้วเลี้ยวขวาค่ะ', cn: '过马路后右转', pron: 'kham thanon laeo liao khwa ka', scene: '指路', diff: '进阶', tone: '日常', gender: 'female', tags: ['出行', '指路'] },
  { id: 175, cat: 'daily-go', thai: 'พาฉันไปที่นี่ได้ไหมคะ', cn: '能带我去这里吗？', pron: 'pha chan pai thi ni dai mai ka', scene: '给司机看地址', diff: '常用', tone: '礼貌', gender: 'female', tags: ['出行', '目的地'] },

  // ===== Part 10.5: 100句·社交用语 =====
  { id: 176, cat: 'daily-social', thai: 'ยินดีที่ได้รู้จักค่ะ', cn: '很高兴认识你', pron: 'yin di thi dai ru chak ka', scene: '初次见面打招呼', diff: '入门', tone: '礼貌', gender: 'female', tags: ['社交', '认识'] },
  { id: 177, cat: 'daily-social', thai: 'ชื่ออะไรคะ', cn: '你叫什么名字？', pron: 'chue a-rai ka', scene: '问对方名字', diff: '入门', tone: '日常', gender: 'female', tags: ['社交', '名字'] },
  { id: 178, cat: 'daily-social', thai: 'ฉันชื่อค่ะ', cn: '我叫……', pron: 'chan chue ka', scene: '自我介绍', diff: '入门', tone: '日常', gender: 'female', tags: ['社交', '名字'] },
  { id: 179, cat: 'daily-social', thai: 'คุณมาเที่ยวคนเดียวหรือคะ', cn: '你一个人来玩吗？', pron: 'khun ma thio khon diao rue ka', scene: '闲聊时问', diff: '常用', tone: '日常', gender: 'female', tags: ['社交', '闲聊'] },
  { id: 180, cat: 'daily-social', thai: 'เราถ่ายรูปด้วยกันได้ไหมคะ', cn: '我们可以合照吗？', pron: 'rao thai rup duai kan dai mai ka', scene: '想和新朋友合照', diff: '常用', tone: '可爱', gender: 'female', tags: ['社交', '合照'] },
  { id: 181, cat: 'daily-social', thai: 'โพสต์ลงIGได้ไหมคะ', cn: '可以发到IG上吗？', pron: 'post long IG dai mai ka', scene: '问合照能否公开发布', diff: '常用', tone: '礼貌', gender: 'female', tags: ['社交', '社交媒体'] },
  { id: 182, cat: 'daily-social', thai: 'ติดตามได้เลยค่ะ', cn: '可以关注我哦', pron: 'tit tam dai loei ka', scene: '分享社交账号', diff: '常用', tone: '可爱', gender: 'female', tags: ['社交', '互关'] },
  { id: 183, cat: 'daily-social', thai: 'น่ารักมากค่ะ', cn: '好可爱', pron: 'na-rak mak ka', scene: '夸人或物可爱', diff: '入门', tone: '可爱', gender: 'female', tags: ['社交', '夸赞'] },
  { id: 184, cat: 'daily-social', thai: 'เก่งมากค่ะ', cn: '好厉害', pron: 'keng mak ka', scene: '夸对方厉害', diff: '入门', tone: '可爱', gender: 'female', tags: ['社交', '夸赞'] },
  { id: 185, cat: 'daily-social', thai: 'คุณใจดีมากค่ะ', cn: '你人真好', pron: 'khun chai di mak ka', scene: '感谢对方善良', diff: '常用', tone: '温柔', gender: 'female', tags: ['社交', '夸赞'] },
  { id: 186, cat: 'daily-social', thai: 'เราแชทกันได้ไหมคะ', cn: '可以聊天吗？', pron: 'rao chat kan dai mai ka', scene: '想和对方聊天', diff: '常用', tone: '可爱', gender: 'female', tags: ['社交', '聊天'] },
  { id: 187, cat: 'daily-social', thai: 'ว่างไหมคะ', cn: '有空吗？', pron: 'wang mai ka', scene: '约人前问有没有空', diff: '入门', tone: '日常', gender: 'female', tags: ['社交', '约人'] },
  { id: 188, cat: 'daily-social', thai: 'ไปเที่ยวด้วยกันเถอะค่ะ', cn: '一起去玩吧', pron: 'pai thio duai kan thoe ka', scene: '约人一起玩', diff: '常用', tone: '可爱', gender: 'female', tags: ['社交', '约玩'] },
  { id: 189, cat: 'daily-social', thai: 'คุณน่ารักมากเลยค่ะ', cn: '你太可爱了', pron: 'khun na-rak mak loei ka', scene: '强烈夸赞', diff: '常用', tone: '可爱', gender: 'female', tags: ['社交', '夸赞'] },
  { id: 190, cat: 'daily-social', thai: 'ขอเบอร์โทรด้วยค่ะ', cn: '可以给我电话号码吗？', pron: 'kho boe tho duai ka', scene: '交换联系方式', diff: '常用', tone: '礼貌', gender: 'female', tags: ['社交', '联系方式'] },
  { id: 191, cat: 'daily-social', thai: 'ฉันมีเรื่องจะปรึกษาค่ะ', cn: '我有事想商量', pron: 'chan mi rueang ja pruek sa ka', scene: '想找人帮忙', diff: '进阶', tone: '日常', gender: 'female', tags: ['社交', '求助'] },
  { id: 192, cat: 'daily-social', thai: 'ขอบคุณสำหรับความช่วยเหลือค่ะ', cn: '谢谢你的帮助', pron: 'khop khun sam-rap kwam chuai lua ka', scene: '感谢帮助', diff: '常用', tone: '礼貌', gender: 'female', tags: ['社交', '感谢'] },
  { id: 193, cat: 'daily-social', thai: 'โชคดีนะคะ', cn: '祝你好运', pron: 'chok di na ka', scene: '祝福对方', diff: '入门', tone: '温柔', gender: 'female', tags: ['社交', '祝福'] },
  { id: 194, cat: 'daily-social', thai: 'คิดถึงนะคะ', cn: '想你哦', pron: 'khit thueng na ka', scene: '对朋友或恋人表达想念', diff: '常用', tone: '温柔', gender: 'female', tags: ['社交', '想念'] },
  { id: 195, cat: 'daily-social', thai: 'รักนะคะ', cn: '爱你哦', pron: 'rak na ka', scene: '对亲密的人说', diff: '入门', tone: '温柔', gender: 'female', tags: ['社交', '爱'] },
];

// 暴露到全局供 app.js 使用
window.APP_DATA = { CATEGORIES, SENTENCES };
